from tkinter import *

def click(event):
    global value
    text=event.widget.cget("text")
    print(text)
    if text=="=":
        try:
            result=eval(value.get())
            value.set(result)
        except Exception as e:
            value.set("Error")
            
    elif text=="Del":
        value.set(value.get()[:-1])
        
    elif text=="C":
        value.set("")
        screen.update()
        
    else:
        value.set(value.get() + text)
        screen.update()
root=Tk()
root.geometry("400x700")
root.title("Calculator")

value=StringVar()
value.set("")
screen=Entry(root, textvar=value, font="lucida 40 bold",bg="lightpink")
screen.pack(fill=X, ipadx=8, ipady=10, padx=8)
f= Frame(root, bg="purple")
b=Button(f, text="Del",padx=0, pady=8, font="lucida 35" )
b.pack(side=LEFT, padx=1, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text="C",padx=8, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text="+",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text="/",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
f.pack()
f= Frame(root, bg="purple")
b=Button(f, text="9",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text="8",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text="7",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text=" *",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
f.pack()

f= Frame(root, bg="purple")
b=Button(f, text="6",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT,padx=3, pady=3)
b.bind("<Button-1>",click)
b=Button(f, text="5",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>", click)
b=Button(f, text="4", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>", click)
b=Button(f, text=" -",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
f.pack()
f= Frame(root, bg="purple")
b=Button(f, text="3",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=4, pady=5)
b.bind("<Button-1>",click)
b=Button(f, text="2",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=4, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="1", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=4, pady=5)
b.bind("<Button-1>", click)
b=Button(f, text="=",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=4, pady=5)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="purple")
b=Button(f, text="%",padx=5, pady=8, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>", click)
b=Button(f, text="0", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>", click)
b=Button(f, text="00", padx=5, pady=8, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>", click)
b=Button(f, text=".",padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=3, pady=3)
b.bind("<Button-1>",click)
f.pack()



root.mainloop()
